install: pip install -U tox-travis codecov
language: python
python:
- 3.6
- 3.5
- 2.7
script: tox
after_success: codecov
notifications:
  slack:
    secure: bQWSFp1qBMgHaWuuozEtJ/h+dN8KaDxnH9HVEK+laXpVDteVJn5vm5rz58e5htcyUPES8TeRcMcL7ZXJFrgSEfTtb85HhAp7mJz1AsKOb7rFdXVuCXxj0fCUUSShFTXYae+h/VE2fYchjxhhttWmKCqbi5Ez63qGTt4lEaDv/38e/SCydRcYLJQMXnQEPWHgCm813A96v8L6gK7LX3onDAwwVFoBJaed9GESycQlGTy+uYfoK9T20CXPFX1OiQKVEb0aEYXaKzod5bm+a0dNnCBvhl9cf692T34utqdW1uWPai+IakuGGlY6S3BF2yq16pg7iHpaMNW7JTn8d52d9QwNFuCUSX3PW1dIttvy2sZOSk1gzWRWuJpderJeVuc9xv/c2kGTHcNNy9PQVjIjLhPvwM206bwdsYdOCv7k/h5P/8mBrwNIxFUz7XRhgr0kI4iFAYAmeAQfLM9ZHV/RtH9YqsCCb/cKC7OeEcXAntoMgFlLjFNH4dPFF8D+TxveTiElSjH7ZoLlg8EOTUbuN0t+jJ2Wlfc8/ybF004bZqY2otvN2oT6+pDP6e8ZqT9y26k8c6iiS9eN+c1JCSSypAkSJKeFmV+2Uk+vwTYFTNkancdOd9mH3/Ir6jAtOL9Ur9HvnvOBMUt75ONZqSn0jX4EoLvmutgWZFh16xKosXg=
