name: PR-Actions

on: pull_request

jobs:
  Linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8' ]
        os: ['ubuntu-latest']
    name: Linting OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Linting
        run: |
          pip install black flake8
          make lint

  PyTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '2.7', '3.4', '3.5', '3.6', '3.7', '3.8']
        pika-version: ['0.13.1', '1.1.0']
        os: ['ubuntu-latest']
#        exclude:
#          - python-version: '3.9'
#            pika-version: '0.13.1'
#          - python-version: '3.7'
#            pika-version: '0.13.1'
#          - python-version: '3.6'
#            pika-version: '0.13.1'
#          - python-version: '3.5'
#            pika-version: '0.13.1'
#          - python-version: '3.4'
#            pika-version: '0.13.1'
    name: PyTests OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - PIKA ${{ matrix.pika-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make Deps
        run: make deps

      - name: Install PIKA
        run: pip install pika==${{ matrix.pika-version }}

      - name: Run Tests
        run: make test

  CodeCoverage:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7']
        os: ['ubuntu-latest']

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Code Coverage OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make Deps
        run: |
          make deps
          pip install pytest
          pip install pytest-cov

      - name: Generate coverage report
        continue-on-error: true
        run: |
          coverage run --source brewtils -m pytest test --tb=no
          coverage report -m
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
